### ISSUE TITLE
GEOSException: Could not parse version info string

### ISSUE THREAD

**Issue by korvinos** [nansencenter/geo-spaas-vagrant#5]

**Comment by mortenwh** [comment]
See also #6 - will you solve this @korvinos?

**Comment by korvinos** [comment]
@mortenwh temporary solution of the issue:
1) Deploy vm (it's gonna fail with geos exception)
2) Go to the deployed vm and update django (conda install -c conda-forge django) 

I'm preparing a bugfix for production now.
